### ISSUE TITLE
RepairCafé Bahnstadt hat keine richtige Online-Präsenz

### ISSUE THREAD

**Issue by LukasFreeze** [heidelberg-makerspace/website#3]
Der [aktuell verwendete Link](http://www.bahnstadttreff.de/pinnwand/reparieren-statt-aussortieren) zum RepairCafé Bahnstadt ist veraltet und führt nur zur Bahnstadttreff-Pinnwand (ohne RepairCafé-Eintrag).

mögliche Lösungen:
- [Dieser link](https://www.bahnstadttreff.de/veranstaltungen/reparieren-statt-aussortieren-0) funktioniert zumindest bis zum nächsten Event am 16. Juni - danach evtl. auch nicht mehr (unsicher)
- [Suche nach "repair OR reparieren"](https://www.bahnstadttreff.de/search/content/repair%20OR%20reparieren) verlinken (unschön)
- Link ganz weglassen, bis es eine eigene Seite zum verlinken gibt (schade)

**Comment by emka** [comment]
Die Suche klingt für mich nach der besten Lösung, um zur gewünschten Information zu kommen. Den Link für jedes Event einzeln anzupassen ist mir zu viel Aufwand.

**Comment by LukasFreeze** [comment]
bahnstadttreff.de ist komplett verschwunden.
